/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaconexion;

import Delegate.SistemaDelegate;
import dto.AlumnosDT;
import dto.UsuarioDT;
import java.awt.Image;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.ir.BreakNode;

/**
 *
 * @author tonny
 */
public class Alumnos extends javax.swing.JFrame {

    /**
     * Creates new form Alumnos
     */
    AlumnosDT dt = new AlumnosDT();
    SistemaDelegate del = new SistemaDelegate();

    private ImageIcon imagen; //declaracion de variables para el metodo de imagen
    private Icon icono;//declaracion de variables para el metodo de imagen

    public Alumnos() {
        initComponents();
        this.pintarImagen(this.lImage1, "src/image/Uamex.jpg");
        this.pintarImagen(this.limage2, "src/image/logo2.jpg");
        this.pintarImagen(this.limage3, "src/image/usuario.png");
        llenadoAlumnos();

    }

    public void llenadoAlumnos() {

        String[] columnas = {"idAlumno", "Nombre", "ApellidoP", "ApellidoM", "Edad", "Eliminar", "Estado"};

        List lista;
        int fila = -1;
        
        try {
            Object[][] data = new Object[del.lsUsuarios().size()][7];
            lista = del.lsAlumnos();
            Iterator it = lista.iterator();
            while (it.hasNext()) {
                dt = (AlumnosDT) it.next();
                fila++;
                data[fila][0] = dt.getIdalumnos();
                data[fila][1] = dt.getNombre();
                data[fila][2] = dt.getApellidoParterno();
                data[fila][3] = dt.getApellidoMaterno();
                data[fila][4] = dt.getEdad();
                //  data[fila][5] = "Modificar";
                data[fila][5] = "Eliminar";
                data[fila][6] = "Activo";

            }
            tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(data, columnas));
            System.out.println("SE HA llenado bien");
        } catch (Exception e) {
            System.out.println(e);
            e.printStackTrace();
            System.out.println("Algo esta mal en la tabla de Alumnos");   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lImage1 = new javax.swing.JLabel();
        limage2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        limage3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuBusqueda = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MenuComprobantes = new javax.swing.JMenu();
        MenuMatricula = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lImage1.setText("jLabel2");
        lImage1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        limage2.setText("jLabel3");
        limage2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(limage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 150, 90));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        tablaAlumnos.setBackground(new java.awt.Color(204, 255, 204));
        tablaAlumnos.setForeground(new java.awt.Color(51, 51, 51));
        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IdAlumnos", "Nombre", "ApellidoP", "ApellidoM", "Edad", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaAlumnos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 650, 320));

        limage3.setText("jLabel4");
        limage3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(limage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 150, 180));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 120, 40));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 120, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UNIVERSIDAD AUTONOMA DEL ESTADO DE MEXICO ");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 530, 90));

        MenuBusqueda.setText("Busqueda");
        MenuBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBusquedaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuBusqueda);
        jMenuBar1.add(jMenu2);

        MenuComprobantes.setText("Comprobantes");
        MenuComprobantes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuComprobantesMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuComprobantes);

        MenuMatricula.setText("Matricula");
        MenuMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMatriculaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuMatricula);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        new RegistroAlumnos().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnAgregarActionPerformed


    private void tablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMouseClicked
        // TODO add your handling code here:
        dt.setIdalumnos(Integer.parseInt(tablaAlumnos.getValueAt(tablaAlumnos.getSelectedRow(), 0).toString()));
        dt.setNombre(tablaAlumnos.getValueAt(tablaAlumnos.getSelectedRow(), 1).toString());
        dt.setApellidoParterno(tablaAlumnos.getValueAt(tablaAlumnos.getSelectedRow(), 2).toString());
        dt.setApellidoMaterno(tablaAlumnos.getValueAt(tablaAlumnos.getSelectedRow(), 3).toString());
        dt.setEdad(Integer.parseInt(tablaAlumnos.getValueAt(tablaAlumnos.getSelectedRow(), 4).toString()));

        String al = "Inactivo";

        /*  if (tablaAlumnos.getSelectedColumn() == 5) {
            if (JOptionPane.showConfirmDialog(this, "Desea Actualizar?", "Actualizar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                try {
                    del.actualizarAlumno(dt);
                    JOptionPane.showMessageDialog(null, "Datos Actualizados");
                } catch (Exception e) {
                    System.out.println("Algo esta Mal hay chequele");
                }

            } else {

                this.dispose();
                new Alumnos().setVisible(true);
            }

        }
         */
        if (tablaAlumnos.getSelectedColumn() == 5) {
            if (JOptionPane.showConfirmDialog(this, "Desea Eliminar el registo?", "Eliminar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                try {
                    del.eliminarAlumno(dt);
                    JOptionPane.showMessageDialog(null, "Registro eliminado");
                    llenadoAlumnos();
                } catch (Exception e) {
                    System.out.println("Algo esta Mal hay chequele");
                }

            } else {
                         
            }

        }else {
            System.out.println("nada");
            
        }

        // tabla1 :es el nombre de tu tabla
        DefaultTableModel tm = (DefaultTableModel) tablaAlumnos.getModel();

        //aca capturo el primer dato de la celda seleccionada 
        String dato = String.valueOf(tm.getValueAt(tablaAlumnos.getSelectedRow(), 6));
          if(dato != al) {
        if (tablaAlumnos.getSelectedColumn() == 6) { 
                  
            if (JOptionPane.showConfirmDialog(this, "Desea DesActivar Este Alumno?", "Activar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                try {

                    tablaAlumnos.setValueAt(al, tablaAlumnos.getSelectedRow(), 6);
                 
                    System.out.println("todo esta bien");
                } catch (Exception e) {
                    System.out.println("Algo esta mal");
                }
            } else {
                new Alumnos().setVisible(true);
                this.dispose();
            }
                          
        }   }  else {
            System.out.println(al);
            if (tablaAlumnos.getSelectedColumn() == 6) {
                  if(dato == al) {
                String al2 = "Activo";
                if (JOptionPane.showConfirmDialog(this, "Desea Activar Este Alumno?", "Activar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    tablaAlumnos.setValueAt(al2, tablaAlumnos.getSelectedRow(), 6);

                }

            }
        }
        }
      
    }//GEN-LAST:event_tablaAlumnosMouseClicked

    private void MenuBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBusquedaMouseClicked
        // TODO add your handling code here:
        new BuscarAlumno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuBusquedaMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void MenuComprobantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuComprobantesMouseClicked
        // TODO add your handling code here:
        new Comprobantes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuComprobantesMouseClicked

    private void MenuMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMatriculaMouseClicked
        try {
            // TODO add your handling code here:
            new MatriculaAlumnos().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_MenuMatriculaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumnos().setVisible(true);
            }
        });
    }

    public void pintarImagen(JLabel lb, String ruta) { //creamos un metodo para poder ajustar la imagen en el label
        this.imagen = new ImageIcon(ruta);//instanciamos los objectos que hemos creado 
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_DEFAULT));//esta instancia es para convertir la imagen a un icono

        lb.setIcon(this.icono);//mandamos a llamar el icono que hemos creado 
        this.repaint();//refres
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuBusqueda;
    private javax.swing.JMenu MenuComprobantes;
    private javax.swing.JMenu MenuMatricula;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lImage1;
    private javax.swing.JLabel limage2;
    private javax.swing.JLabel limage3;
    private javax.swing.JTable tablaAlumnos;
    // End of variables declaration//GEN-END:variables
}
