/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaconexion;

import Delegate.SistemaDelegate;
import dto.AlumnosDT;
import dto.ComprobantesDT;
import java.awt.Image;
import java.util.Iterator;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tonny
 */
public class Comprobantes extends javax.swing.JFrame {

    /**
     * Creates new form Comprobantes
     */
    
    SistemaDelegate del = new SistemaDelegate();
    ComprobantesDT dt = new ComprobantesDT();
          
    
    private ImageIcon imagen; //declaracion de variables para el metodo de imagen
    private Icon icono;//declaracion de variables para el metodo de imagen
    
    public Comprobantes() {
        initComponents();
        this.pintarImagen(this.Limage, "src/image/com.jpg");
        llenadoComprobantes();
    }
    
    
    public void llenadoComprobantes() {

        String[] columnas = {"IdComprobantes", "ninicio", "nfin", "serie", "Tipo de Comprobante", "Modificar", "Eliminar"};

        List lista;
        int fila = -1;
        try {
            Object[][] data = new Object[del.lsComprobante().size()][7];
            lista = del.lsComprobante();
            Iterator it = lista.iterator();
            while (it.hasNext()) {
                dt = (ComprobantesDT) it.next();
                fila++;
                data[fila][0] = dt.getIdcomprobantes();
                data[fila][1] = dt.getnInicio();
                data[fila][2] = dt.getnFin();
                data[fila][3] = dt.getSerie();
                data[fila][4] = dt.getTipoComprobante();
                data[fila][5] = "Modificar";
                data[fila][6] = "Eliminar";
             

            }
            tablaComprobantes.setModel(new javax.swing.table.DefaultTableModel(data, columnas));
            System.out.println("SE HA llenado bien");
        } catch (Exception e) {
            System.out.println("Algo esta mal");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComprobantes = new javax.swing.JTable();
        Limage = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBusqueda = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        MenuMatricula = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Serializacion de Comprobante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 669, -1));

        tablaComprobantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IdComprobantes", "ninecio", "nfin", "serie", "Tipo de Comprobante", "Modificar", "Eliminar"
            }
        ));
        tablaComprobantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaComprobantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaComprobantes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 490, 380));

        Limage.setText("jLabel2");
        getContentPane().add(Limage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 200, 190));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 150, 40));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 150, 40));

        menuBusqueda.setText("BUSQUEDA");
        menuBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBusquedaMouseClicked(evt);
            }
        });
        menuBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBusquedaActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuBusqueda);
        jMenuBar1.add(jMenu2);

        MenuMatricula.setText("MATRICULA");
        MenuMatricula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuMatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMatriculaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuMatricula);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        new RegistroCom().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        new Alumnos().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tablaComprobantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaComprobantesMouseClicked
        // TODO add your handling code here:
        dt.setIdcomprobantes(Integer.parseInt(tablaComprobantes.getValueAt(tablaComprobantes.getSelectedRow(),0).toString()));
        dt.setnInicio(tablaComprobantes.getValueAt(tablaComprobantes.getSelectedRow(),1).toString());
        dt.setnFin(tablaComprobantes.getValueAt(tablaComprobantes.getSelectedRow(), 2).toString());
        dt.setSerie(tablaComprobantes.getValueAt(tablaComprobantes.getSelectedRow(), 3).toString());
        dt.setTipoComprobante(tablaComprobantes.getValueAt(tablaComprobantes.getSelectedRow(), 4).toString());
        
        if(tablaComprobantes.getSelectedColumn()==5){
          if(JOptionPane.showConfirmDialog(this, "Desea Actualizar?", "Actualizar", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
           
              try {
                  del.ActualizarComprobantes(dt);
                  JOptionPane.showMessageDialog(null, "Datos Actualizados");
              } catch (Exception e) {
                  System.out.println("Algo esta Mal hay chequele");  
              }
              
          }else {
          
   this.dispose();
       new Comprobantes().setVisible(true);
          } 
          
        }
        
        if(tablaComprobantes.getSelectedColumn()==6){
          if(JOptionPane.showConfirmDialog(this, "Desea Eliminar el registo?", "Eliminar", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
           
              try {
                  del.EliminarComprobantes(dt);
                  JOptionPane.showMessageDialog(null, "Registro eliminado");
                  llenadoComprobantes();
              } catch (Exception e) {
                  System.out.println("Algo esta Mal hay chequele");  
              }
              
          }else {
          this.dispose();
       new Comprobantes().setVisible(true);
          } 
          
        }
               
    }//GEN-LAST:event_tablaComprobantesMouseClicked

    private void menuBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBusquedaActionPerformed
        // TODO add your handling code here:
        new BusquedaComprobantes().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_menuBusquedaActionPerformed

    private void menuBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBusquedaMouseClicked
        // TODO add your handling code here:
        new BusquedaComprobantes().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBusquedaMouseClicked

    private void MenuMatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMatriculaMouseClicked
        // TODO add your handling code here:
        try {
            new MatriculaAlumnos().setVisible(true);
        } catch (Exception e) {
        }
        this.dispose();
    }//GEN-LAST:event_MenuMatriculaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprobantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprobantes().setVisible(true);
            }
        });
    }
    
    public void pintarImagen(JLabel lb, String ruta) { //creamos un metodo para poder ajustar la imagen en el label
        this.imagen = new ImageIcon(ruta);//instanciamos los objectos que hemos creado 
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_DEFAULT));//esta instancia es para convertir la imagen a un icono

        lb.setIcon(this.icono);//mandamos a llamar el icono que hemos creado 
        this.repaint();//refres
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Limage;
    private javax.swing.JMenu MenuMatricula;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menuBusqueda;
    private javax.swing.JTable tablaComprobantes;
    // End of variables declaration//GEN-END:variables
}
