/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaconexion;

import Delegate.SistemaDelegate;
import config.ComprobantesDao;
import dto.ComprobantesDT;
import dto.MatriculaDT;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ComboBox;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author TONY
 */
public class MatriculaAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form MatriculaAlumnos
     */
    SistemaDelegate del = new SistemaDelegate();
    MatriculaDT dt = new MatriculaDT();
    MatriculaDT dt2 = new MatriculaDT();

    private ImageIcon imagen; //declaracion de variables para el metodo de imagen
    private Icon icono;//declaracion de variables para el metodo de imagen
    public Double saldo;
    
    public MatriculaAlumnos() throws Exception{
        initComponents();
        this.pintarImagen(this.Limage1, "src/image/uaemex2.png");
        this.pintarImagen(this.Limage2, "src/image/matricula.png");
        this.pintarImagen(Lmas, "src/image/mas.png");
        llenarComprobante();
       
    }

    public void LlenarMatricula(MatriculaDT dt) {
        dt.setGrado(ComboGrado.getSelectedItem().toString());
        dt.setSeccion(ComboSeccion.getSelectedItem().toString());
        dt.setHorario(ComboHorario.getSelectedItem().toString());
        dt.setPrecio(Double.parseDouble(txtprecioMatricula.getText()));
        dt.setImporte(Double.parseDouble(txtImporte.getText()));
        Double premat = Double.parseDouble(txtprecioMatricula.getText());
        Double importe = Double.parseDouble(txtImporte.getText());
        Double saldo = premat - importe;
        txtSaldo.setText(String.valueOf(saldo));
        dt.setSaldo(saldo);
        SimpleDateFormat sp = new SimpleDateFormat("yy:MM:dd");
        dt.setFecha(sp.format(cajaDate.getDate().getTime()));
        
        Integer comprobante2 = ComboComprobante.getItemAt(ComboComprobante.getSelectedIndex()).getIdcomprobantes();
       
        dt.setComprobante(comprobante2);
        
        dt.setNumerorecibo(txtRecibo.getText());
        dt.setPreciopension(Integer.parseInt(txtprecioPension.getText()));
        dt.setCantpensiones(Integer.parseInt(conPensiones.getValue().toString()));
    }
    
    
    public void llenarComprobante() throws Exception{
                
        ArrayList<ComprobantesDT> listacomprobantes = (ArrayList<ComprobantesDT>) del.lsComprobante();
         ComboComprobante.removeAllItems();
         
           for(int i = 0; i < listacomprobantes.size(); i++){
             
               ComboComprobante.addItem(new ComprobantesDT(listacomprobantes.get(i).getIdcomprobantes(),listacomprobantes.get(i).getnInicio(),listacomprobantes.get(i).getnFin(),listacomprobantes.get(i).getSerie(),listacomprobantes.get(i).getTipoComprobante()));
           
           }
                   
               
      }
    
     public  void llenadoNumeroComprobante() {
     
      int opcion = ComboComprobante.getSelectedIndex();
     
      switch(opcion){
      
          case 0:{
          
             txtRecibo.setText("12458ADC252");
          }break;
          
          case 1:{
          
             txtRecibo.setText("23456ADC252");
          }break;
          
          
          case 2:{
          
             txtRecibo.setText("2365GFASD12");
          }break;
      
          
          case 3:{
          
             txtRecibo.setText("123ADGT12");
          }break;
          
          case 4:{
          
             txtRecibo.setText("12452ADCF12");
          }break;
      
         default: {
         
            txtRecibo.setText("12345ABCDE");
         }
      
      }
      
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ComboGrado = new javax.swing.JComboBox<>();
        ComboSeccion = new javax.swing.JComboBox<>();
        ComboHorario = new javax.swing.JComboBox<>();
        txtprecioMatricula = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        txtImporte = new javax.swing.JTextField();
        cajaDate = new com.toedter.calendar.JDateChooser();
        txtRecibo = new javax.swing.JTextField();
        txtprecioPension = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Limage1 = new javax.swing.JLabel();
        LabelMatricula = new javax.swing.JLabel();
        Limage2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        conPensiones = new javax.swing.JSpinner();
        Lmas = new javax.swing.JLabel();
        ComboComprobante = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Grado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 80, 27));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Horario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Seccion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("PrecioMatricula");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, 50));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Importe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 50));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Saldo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Fecha");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Comprobante");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("N°Recibo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Precio de Pesion");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Can.Pensiones");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, 30));

        ComboGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1° Semestre", "2° Semestre", "3° Semestre", "4° Semestre", "5° Semestre", "6° Semestre", "7° Semestre", "8° Semestre", "9° Semestre" }));
        getContentPane().add(ComboGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 210, 30));

        ComboSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoralizada", "No Escoralizada" }));
        getContentPane().add(ComboSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 210, 30));

        ComboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7:00 a.m", "8:00 a.m", "7:00 a.m", "9:00 a.m", "1:00 p.m", "2:00 p.m" }));
        getContentPane().add(ComboHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 210, 30));

        txtprecioMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprecioMatriculaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioMatriculaKeyTyped(evt);
            }
        });
        getContentPane().add(txtprecioMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, 30));

        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });
        getContentPane().add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 220, 30));

        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImporteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteKeyTyped(evt);
            }
        });
        getContentPane().add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 220, 30));
        getContentPane().add(cajaDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 220, 30));

        txtRecibo.setEditable(false);
        txtRecibo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 290, 30));

        txtprecioPension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioPensionKeyTyped(evt);
            }
        });
        getContentPane().add(txtprecioPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 290, 30));

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Limage1.setText("jLabel12");
        jPanel1.add(Limage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 250, 140));

        LabelMatricula.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LabelMatricula.setForeground(new java.awt.Color(51, 0, 255));
        LabelMatricula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelMatricula.setText("Matricula Alumnos");
        jPanel1.add(LabelMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 650, 60));

        Limage2.setText("jLabel12");
        jPanel1.add(Limage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 210, 150));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnGuardar.setText("GuardarDatos");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 130, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Cancelar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 140, 50));

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 130, 50));
        jPanel1.add(conPensiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 150, 30));

        Lmas.setText("jLabel12");
        Lmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LmasMouseClicked(evt);
            }
        });
        jPanel1.add(Lmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 60, 50));

        ComboComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboComprobanteActionPerformed(evt);
            }
        });
        jPanel1.add(ComboComprobante, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        try {

            String a = txtImporte.getText();
            String b = txtRecibo.getText();
            String c = txtSaldo.getText();
            String w = txtprecioMatricula.getText();
            String r = txtprecioPension.getText();

            if (a.isEmpty() || b.isEmpty() || c.isEmpty() || w.isEmpty() || r.isEmpty()) {

                JOptionPane.showMessageDialog(null, "Algun campo esta vacio");

            } else {

                
                dt2.setComprobante(ComboComprobante.getItemAt(ComboComprobante.getSelectedIndex()).getIdcomprobantes());

                MatriculaDT dto;

                dto = del.BuscarMatricula(dt2);

                if (dto != null) {
                    JOptionPane.showMessageDialog(null, "Este alumno ya fur gestionacdo en otra institucion");
                    new EscuelaMatricula().setVisible(true);
                } else {

                    LlenarMatricula(dt);
                    del.AgregarMatricula(dt);
                    JOptionPane.showMessageDialog(null, "Datos guardados correctamente");

                }
            }

        } catch (Exception e) {
            System.out.println(e);
            System.out.println("algo esta mal uuhhssss");
           
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        new Alumnos().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void LmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LmasMouseClicked
        // TODO add your handling code here:setVisible(rootPaneCheckingEnabled);
        new RegistroCom().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LmasMouseClicked

    
    private void txtprecioMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioMatriculaKeyReleased
        // TODO add your handling code here:
         String importe = txtprecioMatricula.getText();
        
         if(importe.equals("")==false || importe.matches("0-9]*")) {
            
        
         Double i = Double.parseDouble(importe);
        
         saldo=i;
         txtSaldo.setText(String.valueOf(saldo));
            
        }else{
        
          txtSaldo.setText("Esperando un numero");
        }
        
    }//GEN-LAST:event_txtprecioMatriculaKeyReleased

    private void txtprecioMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioMatriculaKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
        
    }//GEN-LAST:event_txtprecioMatriculaKeyTyped

    private void txtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
        
    }//GEN-LAST:event_txtImporteKeyTyped

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
        
    }//GEN-LAST:event_txtSaldoKeyTyped

    private void txtprecioPensionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioPensionKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        
        if(c<'0' || c>'9') evt.consume();
        
    }//GEN-LAST:event_txtprecioPensionKeyTyped

    private void txtImporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyReleased
        // TODO add your handling code here:
        String importes = txtImporte.getText();
        
         if(importes.equals("")==false || importes.matches("0-9]*")) {
            
        
         Double i = Double.parseDouble(importes);
        
        Double saldo2=this.saldo-i;
         txtSaldo.setText(String.valueOf(saldo2));
            
        }else{
        
          txtSaldo.setText("Esperando un numero");
        }
        
    }//GEN-LAST:event_txtImporteKeyReleased

    private void ComboComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboComprobanteActionPerformed
        // TODO add your handling code here:
        
        llenadoNumeroComprobante();
    }//GEN-LAST:event_ComboComprobanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                try {    
                    new MatriculaAlumnos().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MatriculaAlumnos.class.getName()).log(Level.SEVERE, null, ex);
                }
             
                
            }
        });
    }

    public void pintarImagen(JLabel lb, String ruta) { //creamos un metodo para poder ajustar la imagen en el label
        this.imagen = new ImageIcon(ruta);//instanciamos los objectos que hemos creado 
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_DEFAULT));//esta instancia es para convertir la imagen a un icono

        lb.setIcon(this.icono);//mandamos a llamar el icono que hemos creado 
        this.repaint();//refres
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComprobantesDT> ComboComprobante;
    private javax.swing.JComboBox<String> ComboGrado;
    private javax.swing.JComboBox<String> ComboHorario;
    private javax.swing.JComboBox<String> ComboSeccion;
    private javax.swing.JLabel LabelMatricula;
    private javax.swing.JLabel Limage1;
    private javax.swing.JLabel Limage2;
    private javax.swing.JLabel Lmas;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private com.toedter.calendar.JDateChooser cajaDate;
    private javax.swing.JSpinner conPensiones;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtRecibo;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtprecioMatricula;
    private javax.swing.JTextField txtprecioPension;
    // End of variables declaration//GEN-END:variables
}
