/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaconexion;

import Delegate.SistemaDelegate;
import com.sun.istack.internal.logging.Logger;
import dto.UsuarioDT;
import java.awt.Image;
import java.sql.SQLException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tonny
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
        UsuarioDT dt = new UsuarioDT();
        SistemaDelegate del = new SistemaDelegate();
    
    private ImageIcon imagen; //declaracion de variables para el metodo de imagen
    private Icon icono;//declaracion de variables para el metodo de imagen
    public int usuario; // buscar usuario
    
    public Principal() {
      // this.pintarImagen(this.Limage, "src/image/usuario.png"); //donde esta guardadanuestra imagen
               
        initComponents();
        this.pintarImagen(this.lBagregar, "src/image/usuario.png"); //donde esta guardadanuestra imagen
        llenado();
    }
    
    public void llenado(){
    
        String [] columnas = {"idUsuario", "Nombre", "Usuario", "Contraseña","Modificar","Eliminar"};
        
        List lista;
        int fila=-1;
        try {
           Object[][] data = new Object[del.lsUsuarios().size()][6];
            lista = del.lsUsuarios();
            Iterator it = lista.iterator();
            while(it.hasNext()) {
              dt = (UsuarioDT) it.next();
              fila++;
              data[fila][0]=dt.getIdusuario();
              data[fila][1]=dt.getNombre();
              data[fila][2]=dt.getUsuario();
              data[fila][3]=dt.getContraseña();
              data[fila][4]="Modificar";
              data[fila][5]="Eliminar";
            
            }
        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(data,columnas));
            System.out.println("SE HA llenado bien");
        } catch (Exception e) {
            System.out.println("Algo esta mal");
          
        }
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        lBagregar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idUsuario", "Nombre", "Usuario", "Contraseña", "Actualizar", "Modificar"
            }
        ));
        TablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsuarios);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 600, 350));

        panel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Usuarios");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBuscar.setText("BUSQUEDA");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 760, -1));

        panel3.setBackground(new java.awt.Color(204, 255, 204));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lBagregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lBagregar.setName("lBagregar"); // NOI18N
        lBagregar.setOpaque(true);
        panel3.add(lBagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 190));

        btnAgregar.setBackground(new java.awt.Color(0, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setName("btnAgregar"); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panel3.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 50));

        btnRegresar.setBackground(new java.awt.Color(153, 255, 153));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panel3.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 120, 50));

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 150, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        new Registro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void TablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaUsuariosMouseClicked
        // TODO add your handling code here:
        dt.setIdusuario(Integer.parseInt(TablaUsuarios.getValueAt(TablaUsuarios.getSelectedRow(),0).toString()));
        dt.setNombre(TablaUsuarios.getValueAt(TablaUsuarios.getSelectedRow(), 1).toString());
        dt.setUsuario(TablaUsuarios.getValueAt(TablaUsuarios.getSelectedRow(), 2).toString());
        dt.setContraseña(TablaUsuarios.getValueAt(TablaUsuarios.getSelectedRow(), 3).toString());
        
        if(TablaUsuarios.getSelectedColumn()==4){
          if(JOptionPane.showConfirmDialog(this, "Desea Actualizar?", "Actualizar", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
           
              try {
                  del.actualizarUsuario(dt);
                  JOptionPane.showMessageDialog(null, "Datos Actualizados");
              } catch (Exception e) {
                  System.out.println("Algo esta Mal hay chequele");  
              }
              
          }else {
          
   this.dispose();
       new Principal().setVisible(true);
          } 
          
        }
        
        if(TablaUsuarios.getSelectedColumn()==5){
          if(JOptionPane.showConfirmDialog(this, "Desea Eliminar el registo?", "Eliminar", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
           
              try {
                  del.eliminarUsuario(dt);
                  JOptionPane.showMessageDialog(null, "Registro eliminado");
                  llenado();
              } catch (Exception e) {
                  System.out.println("Algo esta Mal hay chequele");  
              }
              
          }else {
          this.dispose();
       new Principal().setVisible(true);
          } 
          
        }
    }//GEN-LAST:event_TablaUsuariosMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
            try {
                // TODO add your handling code here:
                new Buscar().setVisible(true);
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
     public void pintarImagen(JLabel lb, String ruta) { //creamos un metodo para poder ajustar la imagen en el label
        this.imagen = new ImageIcon(ruta);//instanciamos los objectos que hemos creado 
        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_DEFAULT));//esta instancia es para convertir la imagen a un icono

        lb.setIcon(this.icono);//mandamos a llamar el icono que hemos creado 
        this.repaint();//refres
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBagregar;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
